services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_coolify
      args:
        - NEXT_PUBLIC_LEARNHOUSE_API_URL=${NEXT_PUBLIC_LEARNHOUSE_API_URL}
        - NEXT_PUBLIC_LEARNHOUSE_BACKEND_URL=${NEXT_PUBLIC_LEARNHOUSE_BACKEND_URL}
        - NEXT_PUBLIC_LEARNHOUSE_DOMAIN=${NEXT_PUBLIC_LEARNHOUSE_DOMAIN}
    # Mount the persistent volume to the actual uploads directory (/app/api/content)
    volumes:
      - app-uploads:/app/api/content
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_LEARNHOUSE_MULTI_ORG=${NEXT_PUBLIC_LEARNHOUSE_MULTI_ORG}
      - NEXT_PUBLIC_LEARNHOUSE_DEFAULT_ORG=${NEXT_PUBLIC_LEARNHOUSE_DEFAULT_ORG}
      - NEXT_PUBLIC_LEARNHOUSE_TOP_DOMAIN=${NEXT_PUBLIC_LEARNHOUSE_TOP_DOMAIN}
      - LEARNHOUSE_COOKIE_DOMAIN=${LEARNHOUSE_COOKIE_DOMAIN}
      - LEARNHOUSE_SQL_CONNECTION_STRING=${LEARNHOUSE_SQL_CONNECTION_STRING}
      - LEARNHOUSE_REDIS_CONNECTION_STRING=${LEARNHOUSE_REDIS_CONNECTION_STRING}
      - LEARNHOUSE_CHROMADB_HOST=${LEARNHOUSE_CHROMADB_HOST}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      chromadb:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:80'
      interval: 2s
      timeout: 10s
      retries: 10
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${DEPLOYMENT_NAME:-learnhouse}.rule=Host(`${LEARNHOUSE_DOMAIN}`)"
      - "traefik.http.routers.${DEPLOYMENT_NAME:-learnhouse}.entrypoints=websecure"
      - "traefik.http.services.${DEPLOYMENT_NAME:-learnhouse}.loadbalancer.server.port=80"
      - "traefik.http.routers.${DEPLOYMENT_NAME:-learnhouse}.tls=true"
    networks:
      - backend

  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 4s
      retries: 5
    networks:
      - backend

  redis:
    image: redis:7.2.3
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    # ports:
    #   - "6379:6379"
    volumes:
      - redis-data:/data
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 4s
      retries: 5
    networks:
      - backend

  chromadb:
    image: chromadb/chroma:0.5.16
    environment:
      - CHROMA_SERVER_HOST=localhost  # Only bind to container's localhost
      - CHROMA_SERVER_HTTP_PORT=8000  # Keep internal port consistent
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

volumes:
  postgres-data:
  redis-data:
  app-uploads:

networks:
  backend:
    name: ${DEPLOYMENT_NAME:-learnhouse}-network
    driver: bridge
